### ISSUE TITLE
Email intended for the user is being sent to the admin, and email meant for the admin is being sent to the user.

### ISSUE THREAD

**Issue by uniqueshakya** [Adhish-XD/Car-Rental-System#14]
The email which was meant to send to the user gets send to admin and vice versa.

**Comment by uniqueshakya** [comment]
<img width="538" alt="Screenshot 2024-05-19 at 2 52 15 PM" src="https://github.com/Adhish-XD/VroomCarRental/assets/125380011/f57a7521-be2f-4898-9c13-d5feccda52d7">

**Comment by fhgjnkf** [comment]
Recipients arrays for user and admin were swapped  when defining because of which user got the mail designed for admin and vice versa.I corrected the recipient arrays and now the email goes to the intended role correctly.
<img width="558" alt="Screenshot 2024-05-19 at 4 04 00 PM" src="https://github.com/Adhish-XD/VroomCarRental/assets/125380011/8cd6af7e-7e7e-4fa9-beb4-e0f54da8e3f3">
