### ISSUE TITLE
Error in updating the car’s status.

### ISSUE THREAD

**Issue by uniqueshakya** [Adhish-XD/Car-Rental-System#15]
Once car is booked the status in inventory should be updated as booked but not updating.

**Comment by uniqueshakya** [comment]
<img width="1221" alt="Screenshot 2024-05-19 at 3 15 53 PM" src="https://github.com/Adhish-XD/VroomCarRental/assets/125380011/6f38ba21-443d-4ece-ba56-f0a2efc72b59">

**Comment by fhgjnkf** [comment]
There was a missing field named 'status' in the car schema because of which the data didn't get updated in the car status section. I added the field so now the car's status is getting updated successfully.

<img width="1204" alt="Screenshot 2024-05-19 at 3 15 26 PM" src="https://github.com/Adhish-XD/VroomCarRental/assets/125380011/fd9e048a-6c85-424b-87d2-c55437c505c1">
